sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start"
  - docker build -t BrokenMental/travis-test -f  Dockerfile.dev .

script:
  - docker run -e CI=true BrokenMental/travis-test npm run test -- --coverage

after_success:
  - echo "end"