sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start"
  - docker build -t brokenmental/docker_react -f  Dockerfile.dev .

script:
  - docker run -e CI=true brokenmental/docker_react npm run test -- --coverage

after_success:
  - echo "end"